# Generated by Django 2.2.5 on 2019-10-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H3_works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.IntegerField()),
                ('nickname', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('id_16', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('gif_url', models.CharField(max_length=200)),
                ('video_url', models.CharField(max_length=200)),
                ('video_id', models.CharField(max_length=200)),
                ('width', models.IntegerField()),
            ],
        ),
    ]
