# Generated by Django 2.2.5 on 2019-10-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='h3_works',
            table='video',
        ),
    ]
