# Generated by Django 2.2.5 on 2019-10-05 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('get_video', '0002_auto_20191005_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='h3_works',
            name='jpg_url',
            field=models.CharField(default=datetime.datetime(2019, 10, 5, 13, 16, 3, 85921, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
