# Generated by Django 2.2.5 on 2019-10-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_video', '0003_h3_works_jpg_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h3_works',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='h3_works',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='h3_works',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
