# Generated by Django 2.2.5 on 2019-10-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_video', '0004_auto_20191005_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='h3_works',
            old_name='width',
            new_name='video_with',
        ),
    ]
