# Generated by Django 2.2.5 on 2019-10-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_video', '0005_auto_20191005_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h3_works',
            name='id_16',
            field=models.IntegerField(max_length=16),
        ),
    ]
