# Generated by Django 2.2.5 on 2019-10-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_video', '0006_auto_20191005_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h3_works',
            name='id_16',
            field=models.BigIntegerField(),
        ),
    ]
