# Generated by Django 2.2.5 on 2019-10-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_video', '0007_auto_20191005_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h3_works',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
