# Generated by Django 2.2.5 on 2019-10-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_video', '0008_auto_20191005_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h3_works',
            name='gif_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='h3_works',
            name='jpg_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='h3_works',
            name='nickname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='h3_works',
            name='video_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='h3_works',
            name='video_url',
            field=models.CharField(max_length=300),
        ),
    ]
