# Generated by Django 2.2.5 on 2019-10-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_video', '0009_auto_20191005_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h3_works',
            name='gif_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='h3_works',
            name='jpg_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='h3_works',
            name='video_url',
            field=models.TextField(),
        ),
    ]
